version: "3"

services:
  postgres:
    container_name: postgres_container
    build:
      context: ./postgres
      dockerfile: postgres.dockerfile
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: api_container
    build:
      context: ./api
      dockerfile: api.dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - api

