"""add_user

Revision ID: 4fad1976f2bf
Revises: f4c936560f38
Create Date: 2023-04-07 22:27:40.272601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fad1976f2bf'
down_revision = 'f4c936560f38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
