"""init

Revision ID: f4c936560f38
Revises: 
Create Date: 2023-04-07 20:03:06.903106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c936560f38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_id'), 'human', ['id'], unique=True)
    op.create_table('object',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('actual_user', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['actual_user'], ['human.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['human.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_id'), 'object', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_id'), table_name='object')
    op.drop_table('object')
    op.drop_index(op.f('ix_human_id'), table_name='human')
    op.drop_table('human')
    # ### end Alembic commands ###
